[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9

  [[plugins.inputs.audits]]
    path = ""
    output_path = "reports/main.html"

  [[plugins.inputs.audits]]
    fileName = "about"
    path = ""
    output_path = "reports/about.html"

  [[plugins.inputs.audits]]
    fileName = "dashboard"
    path = ""
    output_path = "reports/dashboard.html"
