[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "about"

  [[plugins.inputs.audits]]
    path = "dashboard"
